[theme]
primaryColor = "#007E9E"              # Teal for good metrics
backgroundColor = "#FFFFFF"            # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for cards
textColor = "#142D54"                 # Navy for text
font = "sans serif"                   # Clean appearance

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
